config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root                       'static_pages#home'
  get     '/home',       to: 'static_pages#home'
  get     '/help',       to: 'static_pages#help'
  get     '/about',      to: 'static_pages#about'
  get     '/contact',    to: 'static_pages#contact'
  get     '/signup',     to: 'users#new'
  post    '/signup',     to: 'users#create'
  get     '/login',      to: 'sessions#new'
  post    '/login',      to: 'sessions#create'
  delete  '/logout',     to: 'sessions#destroy'
  get     '/microposts', to: 'static_pages#home'

  get                        'direct_messages/user_index'
  get                        'direct_messages/to_select'
  get                        'direct_messages/to_search'
  get                        'direct_messages/index'
  post                       'direct_messages/create'
  post                       'direct_messages/hide'
  get                        'direct_messages/fetch_messages'

  # resourcesは主要な7つ(index,create,new,edit,show,update,destroy)のルーティングが自動追加されるが、
  # それ意外のルーティングを、そのリソースに追加したい場合にmemberまたはcollectionを使用する。
  # memberはid有り、collectionはid無しの違いがある。
  # 参考：https://techracho.bpsinc.jp/baba/2014_03_03/15619
  resources :users do
    member do # memberはメソッド
      # following_user GET    /users/:id/following(.:format)          users#following
      # followers_user GET    /users/:id/followers(.:format)          users#followers
      # 下記で上記２つが追加される。memberなので上記のように:idがつく。
      # collectionだと/users/following(.:format)のよう:idがつかない。
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  has_many   :direct_message_stats, dependent: :delete_all
  belongs_to :room

  # 1.pictureが存在しないとき、contentの存在性を検証する
  validates_presence_of :content, unless: :picture?
  # 2.contentが存在しないとき、pictureの存在性を検証する
  validates_presence_of :picture, unless: :content?
  # 上記の２つの検証は、contentとpictureのいずれかが存在する場合は、パスする
  # つまり、contentとpictureの両方が存在しなに場合は、パスしない

  mount_uploader :picture, PictureUploader
  validates :picture_data_uri, size: { maximum: 5.megabytes }, if: :picture?

  def get_state_for(user)
    direct_message_stats.find_by(user: user)
  end

  def received_users
    #users = Array.new
    #room.user_rooms.where.not(user: user).each do |user_room|
    #  users << user_room.user
    #end
    #users

    # roomに所属するユーザ群のうち、自分を除くユーザ群を返す
    # ※bulletでUSE eager loading detectedがでるが、問題無し。
    room.users.where.not(id: user.id)
  end
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController
  before_action :logged_in_user

  def user_index
    @latest_dm_users = current_user.latest_dm_users(10)
    respond_to do |format|
      format.js
    end
  end

  def to_select
    respond_to do |format|
      format.js
    end
  end

  # インクリメンタル検索(JSON版用)
  #def to_search
  #  if params[:query_word].present?
  #    users = current_user.following_search(params[:query_word])
  #    render json: users
  #  end
  #end

  def to_search
    if params[:query_word].present?
      @users = current_user.following_search(params[:query_word])
    else
      @users = []
    end

    respond_to do |format|
      format.js
    end
  end

  def index
    @prev_page_title = params[:page_title]

    @partner = User.find(params[:user_id])
    member = [current_user,@partner]

    @room = Room.find_or_make_by(member)
    @page = 1
    @direct_messages = @room.direct_messages_for(current_user, page: @page, cnt: 5)
    @current_user_id = current_user.id

    respond_to do |format|
      format.js
    end
  end

  def fetch_messages
    @page = params[:page].to_i
    room = Room.find(params[:room_id].to_i)
    @direct_messages = room.direct_messages_for(current_user, page: @page, cnt: 5)
    @current_user_id = current_user.id
  end

  def hide
    direct_message = DirectMessage.find(params[:direct_message][:id])
    current_user.hide_dm(direct_message)
  end

  private

    #def direct_message_params
    #  params.require(:direct_message).permit(:content, :picture,)
    #end
  
end

app/helpers/direct_messages_helper.rb
module DirectMessagesHelper
end

app/views/direct_messages/_direct_message.html.slim
- class_name = "right_side"
- if direct_message.errors.any?
  - direct_message.errors.full_messages.each do |message|
    li class="#{class_name}"
      span
        | [ERORR!] #{message}
- else
  ruby:
    if current_user_id != direct_message.user.id
      class_name = "left_side"
    end

  - if direct_message.content || direct_message.picture?
    li class="#{class_name}"
      / 画像
      span
        - if direct_message.picture?
          = link_to direct_message.picture.url, data: { lightbox: "octocat" }
            = image_tag direct_message.picture.url
          br
      / メッセージ
      span
        - if direct_message.content
          | #{direct_message.content}

      / ゴミ箱アイコン
      = form_with model: DirectMessage.new,
                  url: direct_messages_hide_path,
                  id:    "dm-hide-form",
                  method: :post do |f|
        = f.hidden_field :id, value: direct_message.id
        span.glyphicon.glyphicon-trash.small

app/views/direct_messages/_index.html.slim
/ メッセージエリア
ul.messages data-cur-page="#{@page}" data-fetch-messages-url="#{direct_messages_fetch_messages_path}"
  = render partial: direct_messages, locals: { current_user_id: current_user_id }

/ 入力フォーム
/ current_user_idはActionCableのreceivedで受け取ったdirect_messageが、自分自身のものか判定用
= form_with model: DirectMessage.new,
            url: "" ,
            data: { form: "", room_id: @room.id, current_user_id: current_user_id },
            class: "dm-input-form",
            method: :post do |f|
  .form-children
    .preview-box
    .content-box
      = f.text_field :content, data: { content: "" }, class: "content"
      span class="glyphicon glyphicon-picture"
      span class="glyphicon glyphicon-send" data-send=""
    .hidden-box
      = f.file_field :picture, data: { picture: "" }, class: "picture"
    /= f.submit "Send", data: { send: "" }

coffee:
  cmn_file_size_check('[data-picture]', 5)
  $(document).trigger("direct_messages__index_loaded")

app/views/direct_messages/_modal_header_links.html.slim
- case link_name
- when "create_dm"
  .modal-header-link
    = link_to "Create DM", direct_messages_to_select_path, class: "btn btn-primary modal-header-link", remote: true
- when "back_to_user_index"
  = link_to direct_messages_user_index_path, remote: true do
    span.glyphicon.glyphicon-circle-arrow-left.back_link_icon
- when "back_to_to_select"
  = link_to direct_messages_to_select_path, remote: true do
    span.glyphicon.glyphicon-circle-arrow-left.back_link_icon

app/views/direct_messages/_to_select.html.slim
= text_field_tag "query_word",
                 nil,
                 id: "to_search_form",
                 data: { url: direct_messages_to_search_path },
                 placeholder: "please input destination user."

ul#result.users

app/views/direct_messages/_user_index.html.slim
ul#latest_dm_users.users
  - @latest_dm_users.each do |user|
    li data-url="#{direct_messages_index_path}" data-user-id="#{user.id}" data-page-title="user_index"
      | #{gravatar_for(user,size:40)} #{user.name} @#{user.unique_name}

app/views/direct_messages/fetch_messages.js.slim
- if @direct_messages.present?
  ruby:
    render_data = j(
      render partial: @direct_messages,
      locals: { current_user_id: @current_user_id }
      ) 
  | messages = $(".messages");
  | modal_wrap = $(".iziModal-wrap");
  / <li>要素群をjqueryオブジェクトに変換する
  | list = $("#{render_data}");
  / <li>要素群の最後の要素にクラス付与(そのページの最後の要素を表す)
  | $(list.last()).addClass("page#{@page}-last");
  / html変換用のダミー要素作成
  | dummy = $("<div>");
  / ダミー要素に<li>要素群を挿入(これによりjqueryオブジェクトからhtml要素に変換できる)
  | dummy.append(list.clone(true));
  / jqueryオブジェクトからhtml要素に変換したデータを挿入する
  | messages.prepend(dummy.html());
  / <li>要素群の最後の要素の位置を算出する
  | pos = $(".page#{@page}-last").position();
  / <li>要素群の最後の要素の位置までスクロールする
  | modal_wrap.scrollTop(pos.top);
  | messages.data("cur-page", #{@page});

app/views/direct_messages/index.js.slim
/ 変数modalはapp/views/layouts/_modal.html.slimで定義
| modal.iziModal('setTitle',"#{@partner.name}");

/ 戻るリンク生成・挿入
ruby:
  render_back_link = j( 
    render partial: 'modal_header_links',
    locals: { link_name: "back_to_#{@prev_page_title}" }
    )
| $('.iziModal-header-title').prepend("#{render_back_link}");

/ 内容セット
ruby:
  render_index = render_data = j(
    render partial: 'index',
    locals: {
      current_user_id: @current_user_id,
      direct_messages: @direct_messages
      }
    )
| modal.iziModal('setContent',"#{render_index}");

app/views/direct_messages/to_search.js.slim
| var result = $('#result');
| result.find("li").remove();
- @users.each do |user|
  | result.append('<li data-url="#{direct_messages_index_path}" data-user-id="#{user.id}" data-page-title="to_select">#{gravatar_for(user,size:40)} #{user.name} @#{user.unique_name}</li>');

app/views/direct_messages/to_select.js.slim
/ 変数modalはapp/views/layouts/_modal.html.slimで定義
| modal.iziModal('setTitle',"Create DM");

/ 戻るリンク生成・挿入
ruby:
  render_back_link = j(
    render partial: 'modal_header_links',
    locals: { link_name: "back_to_user_index" }
    )
| $('.iziModal-header-title').prepend("#{render_back_link}");

| modal.iziModal('setContent',"#{j(render('to_select'))}");

app/views/direct_messages/user_index.js.slim
/ 変数modalはapp/views/layouts/_modal.html.slimで定義
| modal.iziModal('setTitle', "Direct Message Users" );
| modal.iziModal('setContent',"#{j(render('user_index'))}");

/ Create DMリンク挿入
ruby:
  render_data = j(
    render partial: 'modal_header_links',
    locals: { link_name: "create_dm" }
    )
| $('.modal-header-link').remove();
| $('.iziModal-header-title').append("#{render_data}");

| if(modal.iziModal('getState') != 'opened') modal.iziModal('open');