config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root                       'static_pages#home'
  get     '/home',       to: 'static_pages#home'
  get     '/help',       to: 'static_pages#help'
  get     '/about',      to: 'static_pages#about'
  get     '/contact',    to: 'static_pages#contact'
  get     '/signup',     to: 'users#new'
  post    '/signup',     to: 'users#create'
  get     '/login',      to: 'sessions#new'
  post    '/login',      to: 'sessions#create'
  delete  '/logout',     to: 'sessions#destroy'
  get     '/microposts', to: 'static_pages#home'

  get                        'direct_messages/user_index'
  get                        'direct_messages/to_select'
  get                        'direct_messages/to_search'
  get                        'direct_messages/index'
  post                       'direct_messages/create'
  post                       'direct_messages/hide'
  get                        'direct_messages/fetch_messages'

  # resourcesは主要な7つ(index,create,new,edit,show,update,destroy)のルーティングが自動追加されるが、
  # それ意外のルーティングを、そのリソースに追加したい場合にmemberまたはcollectionを使用する。
  # memberはid有り、collectionはid無しの違いがある。
  # 参考：https://techracho.bpsinc.jp/baba/2014_03_03/15619
  resources :users do
    member do # memberはメソッド
      # following_user GET    /users/:id/following(.:format)          users#following
      # followers_user GET    /users/:id/followers(.:format)          users#followers
      # 下記で上記２つが追加される。memberなので上記のように:idがつく。
      # collectionだと/users/following(.:format)のよう:idがつかない。
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Userモデルは複数のMicropostモデルを持つ
  # dependent: :destroyは、Userが破棄された場合、それに依存(dependent)して、
  # Micropostsも破棄されるという意味
  has_many :microposts, dependent: :destroy

  # Userモデルは複数のActiveRelationshipモデルを持つ。
  # ここで、ActiveRelationshipというモデルは存在せず、存在するのはRelationshipモデルである。
  # ActiveRelationshipとは、フォローする側からみたRelationshipのことである。
  # has_many :active_relationshipsだけだと、その名称からrailsは存在しないActiveRelationshipsモデルを
  # 探そうとしてしまうため、class_name: "Relationship"と指定することで、そのモデルを明示している。
  # さらに、Userモデルからフォローしている人を検索するためには、Relationshipモデルのfollower_idを
  # 検索しなければいけないため、これを外部キーとして明示するために、foreign_key: "follower_id"を指定している。
  #
  # Userはたくさんのactive_relationships(フォローしている人との関係)を持っている。
  # active_relationshipsのモデルはRelationshipである。
  # Userからactive_relationships(Relationship)を取得するときの外部キーはRelationshipのfollower_idである。
  # → SELECT * FROM relationships WHERE follower_id = 「user.id」
  # Userが削除されれば、Relationshipからもuser.id = relationship.follower_idのレコードが削除される。
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  # Userモデルは複数のPassiveRelationshipモデルを持つ。
  # ここで、PassiveRelationshipというモデルは存在せず、存在するのはRelationshipモデルである。
  # PassiveRelationshipとは、フォローされる側からみたRelationshipのことである。
  # has_many :passive_relationshipsだけだと、その名称からrailsは存在しないPassiveRelationshipsモデルを
  # 探そうとしてしまうため、class_name: "Relationship"と指定することで、そのモデルを明示している。
  # さらに、Userモデルからフォローされている人を検索するためには、Relationshipモデルのfollowed_idを
  # 検索しなければいけないため、これを外部キーとして明示するために、foreign_key: "followed_id"を指定している。
  #
  # Userはたくさんのpassive_relationships(フォローされている人との関係)を持っている。
  # passive_relationshipのモデルはRelationshipである。
  # Userからpassive_relationships(Relationship)を取得するときの外部キーはRelationshipのfollowed_idである。
  # → SELECT * FROM relationships WHERE followed_id = 「user.id」
  # Userが削除されれば、Relationshipからもuser.id = relationship.followed_idのレコードが削除される。
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  # 1人のユーザーはいくつもの「フォローする」「フォローされる」という関係性がある（多対多）
  # ここでは、Userモデルが複数のfollowed(followedはフォローされる人、followedの集合体がfollowing)を持つことを表す。
  # このアプリではfollowingの単体はfollowedとしているが、英語上followingはfollowedの複数形ではないため、
  # railsはfollowingから単数形としてfollowedを推測できない。だからsource: :followedと明示することで、
  # followingの単数形はfollowedと知ることができる。
  # ↓の一文により、Usersモデルは複数のfollowedを持ち、sourceに明示されたfollowedに+ "_id"のfollowed_idを用いて、
  # relationshipsテーブル(active_relationships)から対象のユーザ(followed)を取得できるようになる。
  # なお、これにより、Userがフォローしている人の配列を取得できるfollowingメソッドが使えるようになる。
  #
  # Userはたくさんのfollowing(フォローした人たちの集合)を持つ。
  # followingを取得するときは、active_relationships(フォローしている人との関係)を通す。
  # その際、active_relationships(Relationship)のfollowed_idを参照元とする。
  # → SELECT * FROM users INNER JOIN relationships ON users.id = relationships.followed_id
  #             WHERE relationships.follower_id = 「user.id」
  has_many :following, through: :active_relationships,  source: :followed

  # 1人のユーザーはいくつもの「フォローする」「フォローされる」という関係性がある（多対多）
  # ここでは、Userモデルが複数のfollower(followerはフォローする人、followerの集合体がfollowers)を持つことを表す。
  # followedとfollowdingの関係の時は、followingからfollowedをrailsが推測できないため、source: :followedと
  # 明示していたが、ここでは本来ならsource: :followerを明示する必要はない。敢えて、対照的に比較できるよう明示しているだけ。
  # ↓の一文により、Usersモデルは複数のfollowerを持ち、sourceに明示されたfollowerに+ "_id"のfollower_idを用いて、
  # relationshipsテーブル(passive_relationships)から対象のユーザ(follower)を取得できるようになる。
  # なお、これにより、Userをフォローしている人の配列を取得できるfollowersメソッドが使えるようになる。
  #
  # Userはたくさんのfollowers(フォローされている人たちの集合)を持つ。
  # followersを取得するときは、passive_relationships(フォローされている人との関係)を通す。
  # その際、passive_relationships(Relationship)のfollower_idを参照元とする。
  # → SELECT * FROM users INNER JOIN relationships ON users.id = relationships.follower_id
  #             WHERE relationships.followed_id = 「user.id」
  has_many :followers, through: :passive_relationships, source: :follower

  # dependent: :delete_allは、上記destroyと同じく、それに依存する子オブジェクトも
  # 破棄してくれるが、違いは一括で破棄してくれる点である。
  # destroyはDELETE文を削除する子オブジェクトの件数分発行する。
  # delete_allはDELETE文を1回発行する。
  # 但し、delete_allの場合は、コールバックやバリデーションを介さず、
  # 直接SQLが実行される点に注意。
  has_many :direct_messages,            dependent: :delete_all
  has_many :direct_message_stats,       dependent: :delete_all
  has_many :user_rooms,                 dependent: :delete_all
  has_many :rooms, through: :user_rooms

  has_one  :follower_notification, dependent: :destroy
  accepts_nested_attributes_for :follower_notification

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save   :downcase_email
  before_save   :downcase_unique_name

  # before_saveとの違いは、saveは作成・更新時、createは作成時のみ実行される
  before_create :create_activation_digest

  # app/controllers/users_controller.rbのnewアクションでbuild_follower_notificationしているので不要。
  # ここでafter_createも追加してしまうと、INSERT文が2回走ったあと、DELETE文で消されてしまう。(謎)
  #after_create -> {  create_follower_notification(enabled: false) }

  validates :name, presence: true, length: { maximum: 50 }

  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: CommonRegexp::format_email },
                    uniqueness: { case_sensitive: false }

  validates :unique_name, presence: true, length: { in: Settings.unique_name.length.minimum..Settings.unique_name.length.maximum },
                          format: { with: CommonRegexp::format_unique_name },
                          uniqueness: { case_sensitive: false }

  has_secure_password

  # ここでallow_nil: trueにより空パスワードを許可しているが、has_secure_passwordによる
  # 空パスワードのチェックも行われるため、新規登録時は空パスワードは通らない。
  # なお、以下でallow_nil: trueがないと、新規登録時バリデーションエラーがあった場合に、
  # 二重で空パスワードエラーが発生するという不都合もあった。
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    # ActiveModel::SecurePassword.min_cost はテスト環境だとtrue、それ以外だとfalse
    # 参考：https://qiita.com/shinya_ichinoseki/items/cedde49adc1d1e886195
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  # 第一引数：属性名、第二引数：トークン
  def authenticated?(attribute, token)

    # Usersテーブルの#{attribute}_digest属性から、保存されている
    # ダイジェストを取得する
    digest = send("#{attribute}_digest")

    return false if digest.nil?

    # 下記でトークンがダイジェストと一致するかの論理値を返す
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    # self.update_attributeでもOKだが、
    # selfはモデル内では必須ではない。
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    # self.update_attributeでもOKだが、
    # selfはモデル内では必須ではない。
   
    # update_attributeが2回以上呼ばれる場合は、update_columnsで
    # まとめることができ、データベースへの問い合わせが１回で済む
    # update_attribute(:activated,     true)
    # update_attribute(:activated_at,  Time.zone.now)
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    # UserMailerはapp/mailers/user_mailer.rbに有り
    # account_activationメソッドは引数(userオブジェクト)のuser宛にアカウント有効化メールを送信する
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest, User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    # UserMailerはapp/mailers/user_mailer.rbに有り
    # password_resetメソッドは引数(userオブジェクト)のuser宛にパスワード再設定のメールを送信する
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    # パスワード再設定メール送信時刻 < 現時刻より2時間以上前(早い) の場合、true
    reset_sent_at < 2.hours.ago
  end

  def feed
    # following_idsとはrailsが自動的に生成したメソッドである。
    # Userモデルでhas_many :followingを定義したことで生成される。
    # メソッド名の通り、あるUserがフォローしているユーザのidの配列を返す
    # なお、下記では(?)に直接、following_idsによるidの配列がセットされてしまうように
    # 見えるが、実際は、railsが自動的に配列からidのカンマ区切りの状態に変換してくれる。

    # 書き方１
    # 良くない点：following_idsメソッドでフォローしているユーザをデータベースへ
    # 問い合わせし、さらにMicropost.whereにより再度データベースへ問い合わせている
    # Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
    
    # 書き方２
    # これは書き方１の？ではなくシンボルを使った別の書き方
    # Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
    #                 following_ids: following_ids, user_id: id)

    # 書き方３
    # 良い点：ここのfollowing_idsは書き方１のときのfollowing_idsメソッドではなく
    # ただのSQL文である。これをMicropost.whereの中にいれることで、１文のSQLで
    # あるユーザーがフォローしている全てのユーザIDを取得という意味になり、
    # より効率的にデータを取得できる。
   
    # Relationshipsテーブルから、自分がフォロワーになっている（つまり自分が
    # フォローしている）人たちのID（followed_id）を取得
    #following_ids = "SELECT followed_id FROM relationships
    #                 WHERE follower_id = :user_id"

    # Micropostsテーブルから、上記のID（自分がフォローしている人たちのID）
    # に一致する、または、自分のマイクロポストを取得する
    
    # Micropost.where("user_id IN (#{following_ids})
    #                  OR user_id = :user_id", user_id: id)
    
    Micropost.including_replies(id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    # followingはfollowed(フォローされる側の人)の集合
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    # followingはfollowed(フォローされる側の人)の集合
    following.include?(other_user)
  end

  def following_search(query_word)
    # 開発環境のsqlite3において、LIKE演算子は大文字小文字を区別しないため、
    # LOWERは不要だが、他DBの場合を考慮してLOWERしておく。
    
    # 書き方1
    #r1 = following.where("name        LIKE LOWER(?)", "%#{query_word}%")

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # logged_in_userメソッドはログインユーザかどうか確認し、ログインしていない場合は、login_urlへリダイレクトする。
  # app/controllers/application_controller.rb で定義してある
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    # params[:page]はwill_paginateによって自動的に生成されるパラメータ
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])

    # @userからmicropostsを取得するときにpaginateメソッドで
    # ビューに@micropostsを渡すときの件数(ページ)を制限できる
    # なお、ビュー側には<%= will_paginate %>という埋め込みruby
    # が必要になる。
    @microposts = @user.microposts.paginate(page: params[:page])

    # @userが有効化されていなかったら、root_urlへリダイレクトする
    redirect_to root_url and return unless @user.activated?

    # and returnについて
    # railsでは、1つのアクション内でのrenderメソッドやredirectメソッドは
    # 1度だけにするというルールがある。(複数回呼び出そうとするとエラーになる)
    # そのため、renderやredirectコードのあとにand returnと書くことで
    # 明示的に1度だけ呼ばれるようにすることができる。
    # 参考：https://qiita.com/katsuyuki/items/abf6b8d1cd43915e5586
  end

  def new
    @user = User.new
    @user.build_follower_notification
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user #=> redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    
    # destroyに頼らず手動delete
    #destroy_user(User.find(params[:id]))

    flash[:success] = "User deleted"
    redirect_to users_url
  end

  # @userがフォローしている人たちをページネーションして表示する
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  # @userをフォローしている人たちをページネーションして表示する
  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :unique_name,
                                   follower_notification_attributes: [:id, :enabled]
                                  )
    end

    # beforeアクション
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    #def destroy_user(user)
    #  # 自分の投稿の画像を全削除
    #  remove_images(user.microposts, "picture")
    #  # 自分の投稿を全削除
    #  user.microposts.delete_all
    #  # 自分のフォロー関係を全削除
    #  user.active_relationships.delete_all
    #  # 自分のフォロワー関係を全削除
    #  user.passive_relationships.delete_all
    #  # 自分宛に送られたDM表示状態を全削除
    #  user.direct_message_stats.delete_all
    #  # 自分が送ったDMの表示状態を全削除
    #  direct_messages = user.direct_messages
    #  DirectMessageStat.where(direct_message: direct_messages).delete_all
    #  # 自分のDMの画像を全削除
    #  remove_images(user.direct_messages, "picture")
    #  # 自分のDMを全削除
    #  user.direct_messages.delete_all
    #  # 自分のユーザルームを全削除
    #  user.user_rooms.delete_all
    #  # 自分のユーザを削除
    #  user.delete
    #end

    #def remove_images(active_record_relation, column_name)
    #  active_record_relation.each do |record|
    #    if record.send("#{column_name}?")
    #      record.send("remove_#{column_name}!")
    #      logger.debug "remove_#{column_name}! from #{record.inspect}"
    #    end
    #  end
    #end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像のimageタグを返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.slim
= form_for(current_user.active_relationships.build, remote: true) do |f|
  div
    = hidden_field_tag :followed_id, @user.id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
/ @userがログイン済みユーザーでなかったら
/ (ビューに表示しようとしている@userがcurrent_user(自分)でなかったら)
- unless current_user?(@user)
  #follow_form
    / ログイン済みユーザーが@userをフォローしているか？
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.slim
/- @user.build_follower_notification
= form_for(@user, url: yield(:submit_url)) do |f|

  = render 'shared/error_messages', object: f.object

  = f.label :name
  = f.text_field :name, class: 'form-control'

  = f.label :unique_name
  = f.text_field :unique_name, class: 'form-control'

  = f.label :email
  = f.email_field :email, class: 'form-control'

  = f.label :password
  = f.password_field :password, class: 'form-control'

  = f.label :password_confirmation, "Confirmation"
  = f.password_field :password_confirmation, class: 'form-control'

  = f.fields_for :follower_notification do |f2|
    = f2.check_box :enabled
    = f2.label :enabled, "Follower notification"

  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_unfollow.html.slim
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn"

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |  | 
    = link_to "delete", user, method: :delete, date: { confirm: "You sure?" }

app/views/users/edit.html.slim
- provide(:title, 'Edit user')
- provide(:button_text, 'Save changes')
- provide(:submit_url, user_path )
h1 Update your profile
.row
  .col-md6.col-md-offset-3
    = render 'form'
    .gravatar_edit
      = gravatar_for @user
      / rel="noopener"属性はtarget="_blank"で開いたページから、元のページをjavascriptで
      / window.opener.location = 別サイトのURL などで別ページに遷移させられないように
      / 制限することができる。これは、target="_blank"で開かれたウインドウやタブにより
      / 元ページが一旦隠れてしまっている間に、フィッシングサイトなどの別ページに遷移
      / され、IDやパスワードを盗まれるなどの危険性を回避するための処置。
      / 詳しくは、https://blog.jxck.io/entries/2016-06-12/noopener.html
      a [href="http://gravatar.com/emails" target="_blank" rel="noopener"] change

app/views/users/index.html.slim
- provide(:title, 'All users')
h1 All users

/ will_paginateメソッドはusersビューのコードの中から@usersオブジェクトを
/ 自動的に見つけ出し、利用してくれる。
= will_paginate

ul.users
  / renderメソッドは@usersをUserオブジェクトのリストであると推測してくれる。
  / これにより_user.html.erbパーシャルで各ユーザを出力してくれる。
  = render @users

= will_paginate

app/views/users/new.html.slim
- provide(:title, 'Sign up')
- provide(:button_text, 'Create my account')
- provide(:submit_url, signup_path )
h1 Sign up
.row
  .col-md6.col-md-offset-3
    = render 'form'

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
    section.stats
      = render 'shared/stats'

  .col-md-8

    = render 'follow_form' if logged_in?

    / @user.micropostsが空でない場合
    - if @user.microposts.any?
        h3 Microposts (#{@user.microposts.count})
        ol.microposts
          / 下記の記述で、_micropost.html.erbパーシャルが表示される。
          / これはRailsが@micropostsをMicropostオブジェクトのリスト
          / であると推測し、さらに_micropost.html.erbのパーシャルを
          / 探して表示してくれる。
          = render @microposts

        / 下記の記述で@micropostsのページ表示が実現される
        / なお、will_paginateメソッドを使えるようにするには、
        / モデル側で@micropostsを取得するときにpaginateメソッドで
        / 取得する必要がある。ここではmicropostsはUserモデルに紐付いて
        / いるので、Userコントローラ上のアクションでpaginateメソッドを
        / 使用する。
        / [UsersController#show]
        /   @microposts = @user.microposts.paginate(page: params[:page])

        / また、app/views/users/index.html.slimではwill_paginateメソッドの
        / 引数は何も指定されていないが、それはUsersコントローラの
        / コンテキストにおいて@usersが存在していることを前提としているため。
        / ここでは、Usersコントローラのコンテキストから、@micropostsを自動で
        / 探し出すことはできないため、明示的に@micropostsを渡している。
        = will_paginate @microposts

app/views/users/show_follow.html.slim
/ provideメソッドによりViewからLayoutにデータを渡すことができる
- provide(:title, @title)
.row
  aside.col-md-4

    section.user_info
      = gravatar_for @user
      h1
        = @user.name
      span
        = link_to "view my profile", @user
      span
        b Microposts: #{@user.microposts.count}

    section.stats
      = render 'shared/stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user

  .col-md-8
    h3
      = @title
    - if @users.any?
      ul.users.follow
        = render @users
      = will_paginate