config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root                       'static_pages#home'
  get     '/home',       to: 'static_pages#home'
  get     '/help',       to: 'static_pages#help'
  get     '/about',      to: 'static_pages#about'
  get     '/contact',    to: 'static_pages#contact'
  get     '/signup',     to: 'users#new'
  post    '/signup',     to: 'users#create'
  get     '/login',      to: 'sessions#new'
  post    '/login',      to: 'sessions#create'
  delete  '/logout',     to: 'sessions#destroy'
  get     '/microposts', to: 'static_pages#home'

  get                        'direct_messages/user_index'
  get                        'direct_messages/to_select'
  get                        'direct_messages/to_search'
  get                        'direct_messages/index'
  post                       'direct_messages/create'
  post                       'direct_messages/hide'
  get                        'direct_messages/fetch_messages'

  # resourcesは主要な7つ(index,create,new,edit,show,update,destroy)のルーティングが自動追加されるが、
  # それ意外のルーティングを、そのリソースに追加したい場合にmemberまたはcollectionを使用する。
  # memberはid有り、collectionはid無しの違いがある。
  # 参考：https://techracho.bpsinc.jp/baba/2014_03_03/15619
  resources :users do
    member do # memberはメソッド
      # following_user GET    /users/:id/following(.:format)          users#following
      # followers_user GET    /users/:id/followers(.:format)          users#followers
      # 下記で上記２つが追加される。memberなので上記のように:idがつく。
      # collectionだと/users/following(.:format)のよう:idがつかない。
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      |  The form contains 
      = pluralize(object.errors.count, "error")
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    / renderの引数にインスタンス変数を指定すると、Railsはそれが
    / なんのオブジェクトなのか推測してくれる。@feed_items(app/controllers/static_pages_controller.rbのhomeアクションで定義されている)
    / はcurrent_user.feed.paginate(page: params[:page])であり、
    / current_user.feedはUserモデルのfeedメソッドであり、
    / Micropostオブジェクトを返すので、最終的に_micropost.html.erbを探し出して使用する。
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_micropost_form.html.slim
= form_for(@micropost) do |f|
  / renderの第二引数にハッシュを渡すことで、パーシャルの中でそのハッシュのキー名と
  / 同じ名前の変数が使えるようになり、そのハッシュの値が、変数の中に入る。
  / ここでは、第二引数のハッシュは1組しかないので{}は省略されているが、複数組
  / 渡すことも可能。例) render 'shared/test', {a: 123, b: 100}

  / object: f.objectとという記法について
  / 'shared/error_messages'は@userや@micropost変数を参照して
  / formの入力時にエラーがあるかないかを判定している。
  / つまり'shared/error_messages'がどのコントローラのインスタンス変数を
  / 参照するかは不定である。そこで、objectという変数名を使い、
  / form変数のfのobject、つまりf.object(ここではf.objectは@micropostにあたる)を
  / 渡すことで'shared/error_messages'内で変動するインスタンス変数にアクセスできる
  / ようにしている。
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  span.picture
    / acceptパラメータでファイル選択時に表示されるファイル一覧を
    / 指定したMIMEタイプのものだけにすることができる
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'

coffee:
  cmn_file_size_check('#micropost_picture', 5)

app/views/shared/_stats.html.slim
/ 左辺が未定義または偽ならcurrent_userを代入
- @user ||= current_user
.stats
  / following_user GET    /users/:id/following(.:format)          users#following
  / following_user_path(@user) => /users/#{@user.id}/following
  a href="#{following_user_path(@user)}"
    strong#following.stats
      = @user.following.count
    |  following 
  / followers_user GET    /users/:id/followers(.:format)          users#followers
  / followers_user_path(@user) => /users/#{@user.id}/followers
  a href="#{followers_user_path(@user)}"
    strong#followers.stats
      = @user.followers.count
    |  followers 

app/views/shared/_user_info.html.slim
/ ここのcurrent_userは変数ではなくメソッド。
/ ログインユーザのuserオブジェクトを返す。
/ app/helpers/sessions_helper.rbに定義有り

/ 下の link_toの第二引数は通常 user_path(current_user) だが、current_userに省略できる模様
= link_to gravatar_for(current_user, size: 50), current_user

h1
  = current_user.name

span
  = link_to "view my profile", current_user

/ pluralizeは第一引数の数値に応じて、第二引数の英単語を適切な単数形、複数形に変換した文字列を返す
span
  = pluralize(current_user.microposts.count, "micropost")